package crypto

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/accounts/keystore"
	ethcrypto "github.com/ethereum/go-ethereum/crypto"
)

// TestRealKeystoresDecryptWithGeth validates that keystores generated by this
// project decrypt correctly using go-ethereum's official keystore decoder
// (the same implementation used by geth, Firefly, and other clients).
func TestRealKeystoresDecryptWithGeth(t *testing.T) {
	dir := filepath.Join("..", "..", "keystores")
	files, err := os.ReadDir(dir)
	if err != nil {
		t.Skip("no keystores dir:", err)
	}
	checked := 0
	for _, f := range files {
		if !strings.HasSuffix(f.Name(), ".json") {
			continue
		}
		jsonPath := filepath.Join(dir, f.Name())
		pwdPath := strings.TrimSuffix(jsonPath, ".json") + ".pwd"
		pwd, err := os.ReadFile(pwdPath)
		if err != nil {
			continue // no password sidecar; skip
		}
		data, err := os.ReadFile(jsonPath)
		if err != nil {
			t.Fatal(err)
		}
		// 1) Unmarshal with the project struct (validates field names/types)
		var ks KeyStoreV3
		if err := json.Unmarshal(data, &ks); err != nil {
			t.Fatalf("%s: project struct cannot unmarshal: %v", f.Name(), err)
		}
		// 2) Decrypt with geth's official key derivation (scrypt/pbkdf2 + MAC)
		key, err := keystore.DecryptKey(data, string(pwd))
		if err != nil {
			t.Fatalf("%s: geth DecryptKey failed: %v", f.Name(), err)
		}
		// 3) Verify the derived address matches the keystore address
		addr := ethcrypto.PubkeyToAddress(key.PrivateKey.PublicKey).Hex()
		if !strings.EqualFold(strings.TrimPrefix(addr, "0x"), ks.Address) {
			t.Fatalf("%s: address mismatch: derived %s vs stored %s", f.Name(), addr, ks.Address)
		}
		checked++
	}
	if checked == 0 {
		t.Skip("no keystore json files found")
	}
	t.Logf("validated %d real keystores with go-ethereum official decoder", checked)
}

// TestGeneratedKeystoreRoundTrip encrypts a fresh key and decrypts it with
// go-ethereum, proving end-to-end interop of the writer path.
func TestGeneratedKeystoreRoundTrip(t *testing.T) {
	service := NewKeyStoreService(KeyStoreConfig{Enabled: true})
	ks, password, err := service.GenerateKeyStore(
		"0x6e8d4b6c9f2a1e7d3b5f8c0a4d6e2f1a9b7c5d3e8f0a2b4c6d8e0f1a3b5c7d9e",
		"0x1234567890abcdef1234567890abcdef12345678", "ethereum")
	if err != nil {
		t.Fatal(err)
	}
	data, err := ks.ToJSON()
	if err != nil {
		t.Fatal(err)
	}
	key, err := keystore.DecryptKey(data, password)
	if err != nil {
		t.Fatalf("geth DecryptKey failed on freshly generated keystore: %v", err)
	}
	wantKey, err := ethcrypto.HexToECDSA("6e8d4b6c9f2a1e7d3b5f8c0a4d6e2f1a9b7c5d3e8f0a2b4c6d8e0f1a3b5c7d9e")
	if err != nil {
		t.Fatal(err)
	}
	want := ethcrypto.PubkeyToAddress(wantKey.PublicKey).Hex()
	got := ethcrypto.PubkeyToAddress(key.PrivateKey.PublicKey).Hex()
	if got != want {
		t.Fatalf("decrypted key address %s != expected %s", got, want)
	}
	t.Logf("round-trip OK: geth decrypted keystore for %s", got)
}
